[package]
name = "mongo-driver-leak"
version = "0.1.0"
authors = ["Austin Jones <implAustin@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mongo_driver = "0.13.5"
bson = "1.2"